version: "3.8"
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: app_doctor
    volumes:
        - ~/.docker/postgres/data/:/var/lib/postgres/
        - ~/.docker/postgres/log/:/var/log/postgres/
    ports:
      - "5432:5432"
    networks:
      - postgres-compose-network
    restart: always

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: heliosugano.7022@aluno.saojudas.br
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin

    ports:
      - "5050:80"
    networks:
      - postgres-compose-network
    restart: always

networks:
  postgres-compose-network:
    driver: bridge

volumes:
  postgres-compose-network:
    driver: local
  pgadmin: