version: "3.8"
services:
  # rabbitmq:
  #   image: rabbitmq:3.8-management-alpine
  #   container_name: 'rabbitmq'
  #   ports:
  #     - 5672:5672
  #     - 15672:15672
  #   volumes:
  #     - ~/.docker/rabbitmq/data/:/var/lib/rabbitmq/
  #     - ~/.docker/rabbitmq/log/:/var/log/rabbitmq
  #   networks:
  #     - rabbitmq_go_net
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=admin
  #     - RABBITMQ_DEFAULT_PASS=admin
  #   restart: always

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    volumes:
       - ~/.docker/postgres/data/:/var/lib/postgres/
       - ~/.docker/postgres/log/:/var/log/postgres/
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: always

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: heliosugano.7022@aluno.saojudas.br
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: always

networks:
  # rabbitmq_go_net:
  #   driver: bridge
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: